# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_move', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy',
            fields=[
                ('film_id', models.IntegerField()),
                ('film_name', models.CharField(max_length=100)),
                ('film_type', models.CharField(max_length=100)),
                ('rating_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ratings', models.FloatField()),
            ],
            options={
                'db_table': 'happy',
                'managed': False,
            },
        ),
    ]
